services:
  server-manager:
    image: ghcr.io/mindustrytool/mindustry-server-manager:latest
    container_name: server-manager
    restart: always
    networks:
      - server-manager
      - mindustry-server
    environment:
      SECURITY_KEY: # Get this from mindustry-tool.com
      ACCESS_TOKEN: # Get this from mindustry-tool.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
      - /data:/data

networks:
  mindustry-server:
    driver: bridge
    name: mindustry-server

  server-manager:
    driver: bridge

