name: Build loader jar

on: [push]

jobs:
   buildJar:
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v1
         - name: Set up JDK 17
           uses: actions/setup-java@v4
           with:
              distribution: "temurin"
              java-version: "17"

         - name: Make Gradle wrapper executable
           run: chmod +x ./gradlew

         - name: Build plugin jar
           run: ./gradlew :loader:jar --stacktrace

         - name: Upload built jar file
           uses: actions/upload-artifact@v4
           with:
              name: loader
              path: loader/build/libs/loader.jar

         - uses: "marvinpinto/action-automatic-releases@latest"
           with:
              repo_token: "${{ secrets.GITHUB_TOKEN }}"
              automatic_release_tag: "loader"
              prerelease: true
              title: "Loeader"
              files: |
                 loader/build/libs/loader.jar
